from asyncio import AbstractEventLoop
from typing import Coroutine

class Whisper:
    def __init__(self, length_ms: int, language: str, whisper_model_path: str, vad_model_path: str, save_audio: bool=False, 
                    filename_out: str = "", print_timestamps: bool = True, logger_level: int = 40, 
                    step_ms: int = 0, async_loop: AbstractEventLoop = None) -> None: ...
    def close(self) -> None: ...
    @property
    def is_awaitable(self) -> bool: ...
    def stop_recognize(self) -> None: ...
    def start_recognize(self) -> None: ...
    def recognize(self) -> str: ...
    async def await_result(self) -> str: ...